# NOTE: For GitHub reproducibility, update input paths:
#   modules.fig5_cellchat_build.obj_gr_rds
#   modules.fig5_cellchat_build.obj_oo_rds
# Set mode to 'cellcell_contact' to reproduce the Cell-Cell Contact-only variant.
figure: fig5
modules:
  fig5_cellchat_build:
    obj_gr_rds: data/Fig5/obj_gr_newanno.rds
    obj_oo_rds: data/Fig5/oocyte_edit.rds
    out_dir: results/Fig5/cellchat
    prefix: fig5
    mode: all
    export_comm_tables: true
    gc_cluster_col: seurat_clusters
    gc_sample_col: sample
    gc_celltype_col: celltype
    gc_celltype_levels:
    - GC_Progenitor
    - GC_Preantral_1
    - GC_Preantral_2
    - GC_Cumulus_1
    - GC_Cumulus_2
    - GC_Antral_Mural
    - GC_Atretic
    cluster_to_celltype:
      GC_Progenitor:
      - 8
      GC_Preantral_1:
      - 1
      - 14
      GC_Preantral_2:
      - 6
      - 7
      - 4
      GC_Cumulus_1:
      - 12
      - 13
      GC_Cumulus_2:
      - 10
      - 9
      GC_Antral_Mural:
      - 5
      - 15
      GC_Atretic:
      - 3
      - 0
      - 11
      - 2
    oo_stage_col: stage
    oocyte_exclude_stages:
    - MII
    gc_exclude_celltypes:
    - GC_Atretic
    group_new_levels:
    - EGO
    - GO1
    - GO2
    - GO3
    - FGO
    - GC_Progenitor
    - GC_Preantral_1
    - GC_Preantral_2
    - GC_Cumulus_1
    - GC_Cumulus_2
    - GC_Antral_Mural
    compute_type: triMean
    population_size: false
    seed_use: 888
    min_cells: 10
